/**
 * Theme Registry for Designsystemet
 *
 * This module provides:
 * 1. Theme CSS for inline injection by DesignsystemetProvider
 * 2. Theme color values for Storybook UI theming
 *
 * ## Architecture
 *
 * Theme structure:
 * 1. xala.css - Base Designsystemet tokens (generated by CLI)
 * 2. common-extensions.css - Shared extensions (spacing, typography, buttons, etc.)
 * 3. {theme}-colors.css - Theme-specific color palettes
 *
 * Theme colors are defined in `/designsystemet.config.json` at repo root.
 * This is the SINGLE SOURCE OF TRUTH following Designsystemet docs:
 * @see https://designsystemet.no/en/fundamentals/start-here/own-theme/
 *
 * @example
 * ```typescript
 * import { THEME_CSS, THEME_COLORS, DEFAULT_THEME, type ThemeId } from '@xala-technologies/platform-ui/themes';
 *
 * // Get theme CSS for inline injection
 * const css = THEME_CSS[DEFAULT_THEME];
 *
 * // Get theme colors for Storybook/JS usage
 * const colors = THEME_COLORS[DEFAULT_THEME].light;
 * ```
 */

// Import theme CSS as raw strings
import xalaTheme from './xala.css?raw';
import commonExtensions from './common-extensions.css?raw';
import digilistColors from './digilist-colors.css?raw';
import xaheenColors from './xaheen-colors.css?raw';
import platformColors from './platform-colors.css?raw';

export type ThemeId = 'digdir' | 'altinn' | 'brreg' | 'digilist' | 'xaheen' | 'platform';

// =============================================================================
// THEME COLOR VALUES
// =============================================================================
// These values MUST match designsystemet.config.json at repo root.
// When updating colors, update both files to keep them in sync.
// =============================================================================

/**
 * Theme color structure for Storybook UI.
 * These values match the CSS custom properties in the theme files.
 */
export interface ThemeColorSet {
  accent: {
    base: string;
    hover: string;
    contrast: string;
  };
  neutral: {
    background: string;
    surface: string;
    surfaceHover: string;
    text: string;
    textSubtle: string;
    border: string;
  };
}

export interface ThemeColors {
  name: string;
  light: ThemeColorSet;
  dark: ThemeColorSet;
}

/**
 * Color values for each theme, matching the CSS custom properties.
 * Used by Storybook for UI theming (sidebar, toolbar, docs).
 */
export const THEME_COLORS: Record<ThemeId, ThemeColors> = {
  // Digilist theme - Blue accent (matches digilist-colors.css)
  digilist: {
    name: 'Digilist',
    light: {
      accent: { base: '#2A5280', hover: '#214066', contrast: '#FFFFFF' },
      neutral: {
        background: '#f0f4f8',
        surface: '#FFFFFF',
        surfaceHover: '#eceef2',
        text: '#1e2b3c',
        textSubtle: '#5b6c7f',
        border: '#a9bed6',
      },
    },
    dark: {
      accent: { base: '#9EDBE5', hover: '#b5e5ec', contrast: '#1F2F6E' },
      neutral: {
        background: '#101822',
        surface: '#1b2939',
        surfaceHover: '#1f2f41',
        text: '#e8edf4',
        textSubtle: '#97aac0',
        border: '#375272',
      },
    },
  },

  // Xaheen theme - Gold/olive accent (matches xaheen-colors.css)
  xaheen: {
    name: 'Xaheen',
    light: {
      accent: { base: '#8E8F5A', hover: '#7A7B4D', contrast: '#FFFFFF' },
      neutral: {
        background: '#F2F2ED',
        surface: '#FFFFFF',
        surfaceHover: '#E5E5E0',
        text: '#0B0B0F',
        textSubtle: '#5C6974',
        border: '#DEDED9',
      },
    },
    dark: {
      accent: { base: '#D6D876', hover: '#E6E7A3', contrast: '#0B0B0F' },
      neutral: {
        background: '#0B0B0F',
        surface: '#121216',
        surfaceHover: '#1A1A1F',
        text: '#E6E6E6',
        textSubtle: '#868F97',
        border: '#232323',
      },
    },
  },

  // Digdir theme - Norwegian Design System defaults
  digdir: {
    name: 'Digdir',
    light: {
      accent: { base: '#0062BA', hover: '#004d92', contrast: '#FFFFFF' },
      neutral: {
        background: '#f5f6f7',
        surface: '#FFFFFF',
        surfaceHover: '#e8e9ec',
        text: '#1e2b3c',
        textSubtle: '#68707c',
        border: '#c9c9c9',
      },
    },
    dark: {
      accent: { base: '#76b5fb', hover: '#9ecbfc', contrast: '#1a1a1a' },
      neutral: {
        background: '#1a1a1a',
        surface: '#2a2a2a',
        surfaceHover: '#333333',
        text: '#e0e0e0',
        textSubtle: '#a0a0a0',
        border: '#444444',
      },
    },
  },

  // Altinn theme - uses Digdir defaults
  altinn: {
    name: 'Altinn',
    light: {
      accent: { base: '#0062BA', hover: '#004d92', contrast: '#FFFFFF' },
      neutral: {
        background: '#f5f6f7',
        surface: '#FFFFFF',
        surfaceHover: '#e8e9ec',
        text: '#1e2b3c',
        textSubtle: '#68707c',
        border: '#c9c9c9',
      },
    },
    dark: {
      accent: { base: '#76b5fb', hover: '#9ecbfc', contrast: '#1a1a1a' },
      neutral: {
        background: '#1a1a1a',
        surface: '#2a2a2a',
        surfaceHover: '#333333',
        text: '#e0e0e0',
        textSubtle: '#a0a0a0',
        border: '#444444',
      },
    },
  },

  // Brreg theme - uses Digdir defaults
  brreg: {
    name: 'Bronnysundregistrene',
    light: {
      accent: { base: '#0062BA', hover: '#004d92', contrast: '#FFFFFF' },
      neutral: {
        background: '#f5f6f7',
        surface: '#FFFFFF',
        surfaceHover: '#e8e9ec',
        text: '#1e2b3c',
        textSubtle: '#68707c',
        border: '#c9c9c9',
      },
    },
    dark: {
      accent: { base: '#76b5fb', hover: '#9ecbfc', contrast: '#1a1a1a' },
      neutral: {
        background: '#1a1a1a',
        surface: '#2a2a2a',
        surfaceHover: '#333333',
        text: '#e0e0e0',
        textSubtle: '#a0a0a0',
        border: '#444444',
      },
    },
  },

  // Platform theme - Blue primary with golden accents
  platform: {
    name: 'Platform',
    light: {
      accent: { base: '#3a5ba0', hover: '#2e4a85', contrast: '#FFFFFF' },
      neutral: {
        background: '#f5f7fa',
        surface: '#FFFFFF',
        surfaceHover: '#e3eaf2',
        text: '#1a2238',
        textSubtle: '#4a5568',
        border: '#b0b8c1',
      },
    },
    dark: {
      accent: { base: '#3a5ba0', hover: '#4a6bb0', contrast: '#ffe066' },
      neutral: {
        background: '#181a24',
        surface: '#23243a',
        surfaceHover: '#32334d',
        text: '#e6eaf3',
        textSubtle: '#7a88a1',
        border: '#2d2e3e',
      },
    },
  },
};

/**
 * Get theme colors for a specific theme and color mode.
 */
export function getThemeColors(themeId: ThemeId, mode: 'light' | 'dark'): ThemeColorSet {
  return THEME_COLORS[themeId]?.[mode] || THEME_COLORS.digilist[mode];
}

// =============================================================================
// THEME CSS (for component styling)
// =============================================================================

/**
 * Bundled theme CSS content for inline injection.
 * Each theme is an array of CSS strings that get concatenated.
 *
 * Structure:
 * 1. xalaTheme - Base Designsystemet tokens (required for all)
 * 2. commonExtensions - Shared extensions (spacing, typography, buttons)
 * 3. {theme}Colors - Theme-specific color palette
 */
export const THEME_CSS: Record<ThemeId, string[]> = {
  // Official themes - base + common extensions only
  digdir: [xalaTheme, commonExtensions],
  altinn: [xalaTheme, commonExtensions],
  brreg: [xalaTheme, commonExtensions],
  // Digilist theme - base + extensions + Digilist colors (blue/aqua)
  digilist: [xalaTheme, commonExtensions, digilistColors],
  // Xaheen theme - base + extensions + Xaheen colors (olive/gold)
  xaheen: [xalaTheme, commonExtensions, xaheenColors],
  // Platform theme - base + extensions + Platform colors (blue/gold)
  platform: [xalaTheme, commonExtensions, platformColors],
};

/**
 * Get theme CSS as concatenated string.
 */
export function getThemeCSS(themeId: ThemeId): string {
  const css = THEME_CSS[themeId] || [];
  return css.join('\n');
}

/**
 * Check if theme has CSS to inject.
 * All themes now include at least the base xala.css.
 */
export function hasCustomCSS(themeId: ThemeId): boolean {
  const css = THEME_CSS[themeId];
  return Array.isArray(css) && css.length > 0;
}

/**
 * Check if theme has brand-specific color overrides beyond base + extensions.
 */
export function hasBrandOverrides(themeId: ThemeId): boolean {
  const css = THEME_CSS[themeId];
  return Array.isArray(css) && css.length > 2;
}

// Digilist is the default theme for tenant applications
export const DEFAULT_THEME: ThemeId = 'digilist';

// =============================================================================
// Legacy exports for backwards compatibility
// =============================================================================

/** @deprecated Use THEME_CSS instead */
export const THEMES = THEME_CSS;

/** @deprecated Use getThemeCSS instead */
export function getThemeUrls(_themeId: ThemeId): string[] {
  return [];
}

/** @deprecated Use 'digilist' instead of 'custom' */
export type LegacyThemeId = ThemeId | 'custom';

/** @deprecated Map 'custom' to 'digilist' for backwards compatibility */
export function normalizeThemeId(themeId: LegacyThemeId): ThemeId {
  return themeId === 'custom' ? 'digilist' : themeId as ThemeId;
}
