/**
 * Clarification Types
 * 
 * Types for AI-generated clarification questions with interactive inputs.
 */

// ============================================
// Question Types
// ============================================

export type QuestionType = 'radio' | 'checkbox' | 'select' | 'text' | 'number' | 'scale';

export interface QuestionOption {
    id: string;
    label: string;
    description?: string;
}

export interface ClarificationQuestion {
    /** Unique question ID */
    id: string;
    /** Question type determines the input control */
    type: QuestionType;
    /** The question text */
    question: string;
    /** Optional description/context */
    description?: string;
    /** Options for radio/checkbox/select types */
    options?: QuestionOption[];
    /** Whether this question is required */
    required?: boolean;
    /** Default value */
    defaultValue?: string | string[] | number;
    /** Validation constraints */
    validation?: {
        min?: number;
        max?: number;
        minLength?: number;
        maxLength?: number;
    };
}

// ============================================
// Answer Types
// ============================================

export interface ClarificationAnswer {
    questionId: string;
    value: string | string[] | number;
}

// ============================================
// Session Types
// ============================================

export interface ClarificationSession {
    /** Session ID */
    id: string;
    /** Current step in workflow */
    step: string;
    /** Questions generated by AI */
    questions: ClarificationQuestion[];
    /** User's answers */
    answers: ClarificationAnswer[];
    /** Whether all required questions are answered */
    isComplete: boolean;
    /** Timestamp */
    createdAt: Date;
}

// ============================================
// AI Response Types
// ============================================

export interface ClarificationAIResponse {
    /** Intro message from AI */
    intro?: string;
    /** Generated questions */
    questions: ClarificationQuestion[];
    /** Suggested next steps */
    nextSteps?: string[];
}

// ============================================
// Type Guards
// ============================================

export function isMultiSelectQuestion(q: ClarificationQuestion): boolean {
    return q.type === 'checkbox';
}

export function isSingleSelectQuestion(q: ClarificationQuestion): boolean {
    return q.type === 'radio' || q.type === 'select';
}

export function isTextQuestion(q: ClarificationQuestion): boolean {
    return q.type === 'text';
}
