/**
 * Theme Registry for Designsystemet
 *
 * This module provides:
 * 1. Theme CSS for inline injection by DesignsystemetProvider
 * 2. Theme color values for Storybook UI theming
 *
 * ## Architecture
 *
 * Theme colors are defined in `/designsystemet.config.json` at repo root.
 * This is the SINGLE SOURCE OF TRUTH following Designsystemet docs:
 * @see https://designsystemet.no/en/fundamentals/start-here/own-theme/
 *
 * The workflow is:
 * 1. Define themes in `designsystemet.config.json`
 * 2. Run CLI to generate tokens: `npx @digdir/designsystemet@latest tokens create`
 * 3. Run CLI to generate CSS: `npx @digdir/designsystemet@latest tokens build`
 * 4. Extension files (xala-extensions.css, xaheen-extensions.css) override generated tokens
 *
 * The THEME_COLORS below must match the config values for Storybook UI theming.
 *
 * @example
 * ```typescript
 * import { THEME_CSS, THEME_COLORS, DEFAULT_THEME, type ThemeId } from '@xala-technologies/platform-ui/themes';
 *
 * // Get theme CSS for inline injection
 * const css = THEME_CSS[DEFAULT_THEME];
 *
 * // Get theme colors for Storybook/JS usage
 * const colors = THEME_COLORS[DEFAULT_THEME].light;
 * ```
 */

// Import theme CSS as raw strings
// Note: ?raw suffix is needed for Vite (Storybook) compatibility
// tsup handles this via esbuild plugin that strips ?raw and loads as text
// xala.css is generated by Designsystemet CLI, extensions override it
import xalaTheme from './xala.css?raw';
import xalaExtensions from './xala-extensions.css?raw';
import xaheenExtensions from './xaheen-extensions.css?raw';

export type ThemeId = 'digdir' | 'altinn' | 'brreg' | 'custom' | 'xaheen';

// =============================================================================
// THEME COLOR VALUES
// =============================================================================
// These values MUST match designsystemet.config.json at repo root.
// When updating colors, update both files to keep them in sync.
// =============================================================================

/**
 * Theme color structure for Storybook UI.
 * These values match the CSS custom properties in the theme files.
 */
export interface ThemeColorSet {
  accent: {
    base: string;
    hover: string;
    contrast: string;
  };
  neutral: {
    background: string;
    surface: string;
    surfaceHover: string;
    text: string;
    textSubtle: string;
    border: string;
  };
}

export interface ThemeColors {
  name: string;
  light: ThemeColorSet;
  dark: ThemeColorSet;
}

/**
 * Color values for each theme, matching the CSS custom properties.
 * Used by Storybook for UI theming (sidebar, toolbar, docs).
 */
export const THEME_COLORS: Record<ThemeId, ThemeColors> = {
  // Xala/Custom theme - Blue accent (matches xala-extensions.css)
  custom: {
    name: 'Xala',
    light: {
      accent: { base: '#2A5280', hover: '#214066', contrast: '#FFFFFF' },
      neutral: {
        background: '#f0f4f8',
        surface: '#FFFFFF',
        surfaceHover: '#eceef2',
        text: '#1e2b3c',
        textSubtle: '#5b6c7f',
        border: '#a9bed6',
      },
    },
    dark: {
      accent: { base: '#76b5fb', hover: '#9ecbfc', contrast: '#0F1F33' },
      neutral: {
        background: '#101822',
        surface: '#1b2939',
        surfaceHover: '#1f2f41',
        text: '#e8edf4',
        textSubtle: '#97aac0',
        border: '#375272',
      },
    },
  },

  // Xaheen theme - Gold/olive accent (matches xaheen-extensions.css)
  xaheen: {
    name: 'Xaheen',
    light: {
      accent: { base: '#8E8F5A', hover: '#7A7B4D', contrast: '#FFFFFF' },
      neutral: {
        background: '#F2F2ED',
        surface: '#FFFFFF',
        surfaceHover: '#E5E5E0',
        text: '#0B0B0F',
        textSubtle: '#5C6974',
        border: '#DEDED9',
      },
    },
    dark: {
      accent: { base: '#D6D876', hover: '#E6E7A3', contrast: '#0B0B0F' },
      neutral: {
        background: '#0B0B0F',
        surface: '#121216',
        surfaceHover: '#1A1A1F',
        text: '#E6E6E6',
        textSubtle: '#868F97',
        border: '#232323',
      },
    },
  },

  // Digdir theme - Norwegian Design System defaults
  digdir: {
    name: 'Digdir',
    light: {
      accent: { base: '#0062BA', hover: '#004d92', contrast: '#FFFFFF' },
      neutral: {
        background: '#f5f6f7',
        surface: '#FFFFFF',
        surfaceHover: '#e8e9ec',
        text: '#1e2b3c',
        textSubtle: '#68707c',
        border: '#c9c9c9',
      },
    },
    dark: {
      accent: { base: '#76b5fb', hover: '#9ecbfc', contrast: '#1a1a1a' },
      neutral: {
        background: '#1a1a1a',
        surface: '#2a2a2a',
        surfaceHover: '#333333',
        text: '#e0e0e0',
        textSubtle: '#a0a0a0',
        border: '#444444',
      },
    },
  },

  // Altinn theme - uses Digdir defaults
  altinn: {
    name: 'Altinn',
    light: {
      accent: { base: '#0062BA', hover: '#004d92', contrast: '#FFFFFF' },
      neutral: {
        background: '#f5f6f7',
        surface: '#FFFFFF',
        surfaceHover: '#e8e9ec',
        text: '#1e2b3c',
        textSubtle: '#68707c',
        border: '#c9c9c9',
      },
    },
    dark: {
      accent: { base: '#76b5fb', hover: '#9ecbfc', contrast: '#1a1a1a' },
      neutral: {
        background: '#1a1a1a',
        surface: '#2a2a2a',
        surfaceHover: '#333333',
        text: '#e0e0e0',
        textSubtle: '#a0a0a0',
        border: '#444444',
      },
    },
  },

  // Brreg theme - uses Digdir defaults
  brreg: {
    name: 'Brønnøysundregistrene',
    light: {
      accent: { base: '#0062BA', hover: '#004d92', contrast: '#FFFFFF' },
      neutral: {
        background: '#f5f6f7',
        surface: '#FFFFFF',
        surfaceHover: '#e8e9ec',
        text: '#1e2b3c',
        textSubtle: '#68707c',
        border: '#c9c9c9',
      },
    },
    dark: {
      accent: { base: '#76b5fb', hover: '#9ecbfc', contrast: '#1a1a1a' },
      neutral: {
        background: '#1a1a1a',
        surface: '#2a2a2a',
        surfaceHover: '#333333',
        text: '#e0e0e0',
        textSubtle: '#a0a0a0',
        border: '#444444',
      },
    },
  },
};

/**
 * Get theme colors for a specific theme and color mode.
 */
export function getThemeColors(themeId: ThemeId, mode: 'light' | 'dark'): ThemeColorSet {
  return THEME_COLORS[themeId]?.[mode] || THEME_COLORS.custom[mode];
}

// =============================================================================
// THEME CSS (for component styling)
// =============================================================================

/**
 * Bundled theme CSS content for inline injection.
 * Each theme is an array of CSS strings that get concatenated.
 *
 * NOTE: xalaTheme (xala.css) contains the core Designsystemet CSS variables
 * that are REQUIRED for all themes. It is generated by the Designsystemet CLI.
 * Extensions override specific color values for each brand.
 */
export const THEME_CSS: Record<ThemeId, string[]> = {
  // Official themes - use base xala.css (contains all DS tokens)
  digdir: [xalaTheme],
  altinn: [xalaTheme],
  brreg: [xalaTheme],
  // Custom Xala theme - base + Xala color overrides
  custom: [xalaTheme, xalaExtensions],
  // Xaheen theme - base + Xaheen color overrides (Oscura-inspired)
  xaheen: [xalaTheme, xaheenExtensions],
};

/**
 * Get theme CSS as concatenated string.
 */
export function getThemeCSS(themeId: ThemeId): string {
  const css = THEME_CSS[themeId] || [];
  return css.join('\n');
}

/**
 * Check if theme has CSS to inject.
 * All themes now include at least the base xala.css.
 */
export function hasCustomCSS(themeId: ThemeId): boolean {
  const css = THEME_CSS[themeId];
  return Array.isArray(css) && css.length > 0;
}

/**
 * Check if theme has brand-specific overrides beyond the base.
 */
export function hasBrandOverrides(themeId: ThemeId): boolean {
  const css = THEME_CSS[themeId];
  return Array.isArray(css) && css.length > 1;
}

// Custom is the default theme for tenant applications
export const DEFAULT_THEME: ThemeId = 'custom';

// Legacy exports for backwards compatibility (deprecated)
/** @deprecated Use THEME_CSS instead */
export const THEMES = THEME_CSS;
/** @deprecated Use getThemeCSS instead */
export function getThemeUrls(_themeId: ThemeId): string[] {
  // Return empty array - URLs are no longer used
  return [];
}
